### ISSUE TITLE
stroke width

### ISSUE THREAD

**Issue by amirmamaghani** [erkkah/margaid#1]
how can I change stroke width from default 3px to 1px? Thanks!

**Comment by erkkah** [comment]
Hi! I just pushed a fix that lets you do just that using the `UsingStrokeWidth` option.

```go
diagram.Line(testSeries, m.UsingAxes(m.XAxis, m.YAxis), m.UsingMarker("square"), m.UsingStrokeWidth(1))
```

**Comment by janpfeifer** [comment]
hi @erkkah , first thanks for the library, the plots look great!

I was trying the demo and the default `go get github.com/erkkah/margaid` would always get the v0.0.2, without the `UsingStrokeWidth`. I had to manually do a `go get github.com/erkkah/margaid@...<commit hash>...` to make it work.

Any chances you could do a new release ?

Looking at it I suspect that the "v0.1" release/tag didnt' work -- Go seems to require 3 numbers. So maybe a "v0.1.0" release would fix it ?

**Comment by erkkah** [comment]
Hi @janpfeifer. Thanks for the heads-up. Will take a look!

**Comment by erkkah** [comment]
That seemed to do the trick, @janpfeifer, thanks!

```
$ go get github.com/erkkah/margaid
go: added github.com/erkkah/margaid v0.1.0
```
