### ISSUE TITLE
Option to set a solid background ?

### ISSUE THREAD

**Issue by janpfeifer** [erkkah/margaid#2]
hi @erkkah,

Just a detail, but the examples in the README.md are not very visible if in dark mode. I was wondering if there is an easy way to add an option to set a solid background (default to white instead of transparent?) in the generated SVG ? 

cheers, and thanks for the library! :)

**Comment by janpfeifer** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/7460115/215265798-1a73b7d4-ff7e-4371-8c4b-290d36692b4b.png">

**Comment by erkkah** [comment]
If you want, check out the PR. It should fix the issue.

**Comment by janpfeifer** [comment]
Thank you very much @erkkah ! It worked great, already tested on my project.

ps.: I thought I had replied before but I may have forgotten to click on send/comment. Apologies if this comes duplicate.

**Comment by janpfeifer** [comment]
hi @erkkah , I just released [GoNB](https://github.com/janpfeifer/gonb), a Jupyter kernel for Go, and [the tutorial](https://github.com/janpfeifer/gonb/blob/e15ac2e8e3fe/examples/tutorial.ipynb) features Margaid, with the background color set. Thx again. [Here a Reddit post](https://www.reddit.com/r/golang/comments/10y42xd/gonb_a_new_jupyter_notebook_kernel_for_go/) in case you are interested.

**Comment by erkkah** [comment]
@janpfeifer, that's awesome! Great work, and thanks. 🙏
